# syntax=docker/dockerfile:1
FROM python:3.9

RUN mkdir /notebooks
WORKDIR /notebooks

COPY ./auto_viml /notebooks/auto_viml
COPY ./datasets/classification /notebooks/datasets/classification
COPY ./datasets/regression /notebooks/datasets/regression

RUN pip install autoviml notebook --upgrade --ignore-installed

CMD ["jupyter","notebook","--ip=0.0.0.0","--port=8888","--no-browser","--allow-root", "--notebook-dir=/notebooks"]

EXPOSE 8888