# syntax=docker/dockerfile:1
FROM continuumio/miniconda3:4.10.3p1

RUN mkdir /notebooks
WORKDIR /notebooks
COPY ./pycaret /notebooks/pycaret
COPY ./datasets /notebooks/datasets

RUN conda create --name pycaret python=3.8
SHELL ["conda", "run", "-n", "pycaret", "/bin/bash", "-c"]
RUN pip install pycaret
RUN conda install -c anaconda jupyter

CMD ["conda", "run", "-n", "pycaret", "jupyter","notebook","--ip=0.0.0.0","--port=8888","--no-browser","--allow-root", "--notebook-dir=/notebooks"]

EXPOSE 8888