# syntax=docker/dockerfile:1
FROM python:3.9

RUN mkdir /notebooks
RUN mkdir /notebooks/classification
RUN mkdir /notebooks/regression
WORKDIR /notebooks

COPY ./tpot /notebooks/tpot
COPY ./datasets/classification /notebooks/datasets/classification
COPY ./datasets/regression /notebooks/datasets/regression

RUN python -m pip install --upgrade pip
RUN pip install numpy scipy scikit-learn notebook pandas joblib torch torchvision deap update_checker tqdm stopit xgboost tpot

CMD ["jupyter","notebook","--ip=0.0.0.0","--port=8888","--no-browser","--allow-root", "--notebook-dir=/notebooks"]

EXPOSE 8888